export const messageVariants = {
  greeting: [
    "{greeting}! I’m glad you’re here. What shall we explore today?",
    "{greeting}! Your notes are here, and so am I.",
    "{greeting}! Let’s find one interesting thing to learn.",
    "{greeting}! A little time for your curious mind?",
    "{greeting}! Settle in. We can take this at your pace.",
    "{greeting}! Ready for another little discovery?",
    "{greeting}! Bring your curiosity; we’ll start from there.",
    "{greeting}! Let’s give those ideas a little attention.",
    "{greeting}! One small step is a perfectly good plan.",
    "{greeting}! It’s nice to share a learning moment with you.",
  ],
  empty: [
    "Your library is a fresh page. Add your first reviewer and let’s begin.",
    "Have a note you want to remember? Turn it into your first reviewer.",
    "No reviewers yet. A few questions from your notes are enough to start.",
    "Let’s give your ideas a home. Your first reviewer can be small.",
    "Pick a topic you’re curious about, then add a few cards to explore it.",
    "Your learning space is ready. Add a reviewer whenever inspiration arrives.",
    "Start with something familiar. A short reviewer can help you settle in.",
    "Got a lesson on your mind? Make a reviewer for the parts you want to keep.",
    "Your first set doesn’t need to be perfect. You can edit it as you learn.",
    "A question, an answer, a first card. That’s enough to open your library.",
  ],
  library: [
    "You’ve made room for {library}. There’s a little world of ideas here.",
    "Your shelves hold {library}. Which idea catches your eye today?",
    "You have {library} ready to explore, one card at a time.",
    "Look around your library: {library}, all in your own learning space.",
    "With {library}, you can choose a small corner to focus on today.",
    "There are {library} in your collection. Let’s make a few feel familiar.",
    "Your collection has {library}. You don’t need to tackle everything at once.",
    "I see {library} here. Pick the set that feels useful right now.",
    "You’ve gathered {library}. A quick revisit might reveal a new connection.",
    "{library} are waiting in your library. Choose where your curiosity leads.",
  ],
  resume: [
    "Want to pick up {reviewer}? Your study desk is ready below.",
    "You last opened {reviewer}. Shall we reconnect with those ideas?",
    "{reviewer} is on your study desk. A few cards can be a gentle return.",
    "Feel like continuing {reviewer}, or is something else calling today?",
    "Your last study set was {reviewer}. It’s here whenever you want it.",
    "We can revisit {reviewer}. Try recalling one idea before flipping a card.",
    "{reviewer} is where you left off. No need to search for it again.",
    "Ready for another look at {reviewer}? Your next step is just below.",
    "Keep {reviewer} going, or choose a new direction. It’s your study time.",
    "A little reminder: {reviewer} was your latest stop in the library.",
  ],
  organize: [
    "You have {organization}. Pick an idea you’d like to get to know better.",
    "Your library has {organization}. Give related ideas a place together.",
    "With {organization}, you can arrange your learning your own way.",
    "I see {organization}. Choose a reviewer to put it on your study desk.",
    "There are {organization} here. A clear home for notes can make revisiting easier.",
    "You’ve set up {organization}. Which part of your library needs attention today?",
    "{organization} help map your learning space. Start wherever feels useful.",
    "You have {organization}. Grouping related reviewers can make a lesson easier to find.",
    "Your collection spans {organization}. Let’s choose a place to begin.",
    "With {organization} in your library, there’s room to shape your own routine.",
  ],
  activity: [
    "You’ve finished {sessions} today. That’s time you made for yourself.",
    "{sessions} completed today! A little pause is welcome, too.",
    "You made space for {sessions} today. Give yourself some credit.",
    "Today holds {sessions} of completed practice. Those small efforts count.",
    "You’ve already completed {sessions} today. Continue only if it feels helpful.",
    "{sessions} finished today. What’s one idea you’d like to carry with you?",
    "Your activity shows {sessions} today. Take a breath before the next step.",
    "That’s {sessions} for today. Learning can include a well-earned break.",
    "You’ve wrapped up {sessions} today. Let those ideas settle for a moment.",
    "{sessions} completed today. You showed up for your own learning.",
  ],
  badges: [
    "You’ve earned {badges}! Your achievements keep those little wins together.",
    "There are {badges} in your collection. Each marks a step you took.",
    "Your {badges} are saved in Achievements. Take a look when you feel like celebrating.",
    "You’ve unlocked {badges}. No need to rush toward the next one.",
    "{badges} earned along the way! Enjoy the progress you’ve made.",
    "Your achievement shelf holds {badges}. That’s part of your learning story.",
    "A little celebration: you have {badges} to your name.",
    "You’ve collected {badges}. Let the next milestone arrive at your pace.",
    "I spotted {badges} in your achievements. Those wins are yours to keep.",
    "{badges} unlocked! A small reminder of what you’ve already done.",
  ],
  closing: [
    "I’ll be here. Choose the next step that feels right for you.",
    "One useful idea is enough for a good little study moment.",
    "Try explaining a card out loud. Sometimes that makes an idea click.",
    "Take your time with the tricky parts. Familiarity grows through revisiting.",
    "A short, thoughtful session can be a lovely way to begin.",
    "You can keep going, switch topics, or take a break. This is your space.",
    "Before you start, pick one thing you’d like to understand a little better.",
    "Let curiosity lead for a while. You don’t have to know everything today.",
    "Your notes can grow with your understanding. Make them your own.",
    "Ready whenever you are. Let’s keep learning one small piece at a time.",
  ],
} as const;

export function messageVariant(
  category: keyof typeof messageVariants,
  seed: number,
  values: Record<string, string> = {},
): string {
  const options = messageVariants[category];
  const offset = Object.keys(messageVariants).indexOf(category) * 7;
  const template =
    options[(Math.abs(Math.trunc(seed)) + offset) % options.length];
  return template.replace(
    /\{(\w+)\}/g,
    (placeholder, key: string) => values[key] ?? placeholder,
  );
}
