import type { CSSProperties } from "react";
import {
  Trophy,
  Menu,
  House,
  BookOpen,
  FolderOpen,
  Tags,
  ClipboardCheck,
  ChartNoAxesCombined,
  Settings2,
  Plus,
  ArrowRight,
  Search,
  Flame,
  Check,
  X,
  Download,
  Sparkles,
  Clock,
  Sun,
  Moon,
  Monitor,
  ShieldCheck,
  FileText,
  CircleHelp,
  Info,
  Upload,
  Trash2,
  Palette,
  Target,
  Laptop,
  Heart,
  Grid2X2,
  List,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const icons: Record<string, LucideIcon> = {
  menu: Menu,
  Mira: Sparkles,
  Home: House,
  Reviewers: BookOpen,
  Topics: Tags,
  Folders: FolderOpen,
  Docs: FileText,
  Quizzes: ClipboardCheck,
  Activity: ChartNoAxesCombined,
  Achievements: Trophy,
  Settings: Settings2,
  plus: Plus,
  arrow: ArrowRight,
  search: Search,
  flame: Flame,
  check: Check,
  close: X,
  download: Download,
  spark: Sparkles,
  clock: Clock,
  light: Sun,
  dark: Moon,
  system: Monitor,
  Privacy: ShieldCheck,
  Terms: FileText,
  Guide: CircleHelp,
  About: Info,
  upload: Upload,
  trash: Trash2,
  palette: Palette,
  target: Target,
  laptop: Laptop,
  heart: Heart,
  grid: Grid2X2,
  list: List,
  up: ChevronUp,
  down: ChevronDown,
  previous: ChevronLeft,
  next: ChevronRight,
};
export function Icon({
  name,
  size = 20,
  style,
}: {
  name: string;
  size?: number;
  style?: CSSProperties;
}) {
  const Glyph = icons[name] || BookOpen;
  return (
    <Glyph size={size} style={style} strokeWidth={1.7} aria-hidden="true" />
  );
}
